# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "===Setting up==="
    sudo apt-get update
    echo "C++ compiler: "
    g++ --version
  displayName: 'Setup environment'

- script: |
    cd test
    make all
  displayName: 'Build and test'